// GENERATED by scripts/gen-board-metrics.mjs — do not edit by hand.
//
// Natural width/height of each flag asset, read from its PNG header, so a board
// can size a flag server-side without waiting for the image. Regenerate after
// adding or replacing anything in public/flags.

export const FLAG_RATIO: Record<string, number> = {
  "ALG": 1.4953,
  "ARG": 1.6,
  "AUS": 2,
  "BRA": 1.4286,
  "BRN": 1.6667,
  "BUL": 1.6667,
  "CHI": 1.4953,
  "CHN": 1.4953,
  "CRO": 2,
  "CUB": 2,
  "CZE": 1.4953,
  "DOM": 1.4953,
  "EGY": 1.4953,
  "ESP": 1.4953,
  "FRA": 1.4953,
  "HKG": 1.4953,
  "INA": 1.4953,
  "IND": 1.4953,
  "IRI": 1.7582,
  "IRQ": 1.4953,
  "ITA": 1.4953,
  "JPN": 1.4953,
  "KAZ": 2,
  "KOR": 1.4953,
  "MEX": 1.7582,
  "NZL": 2,
  "OMA": 1.7582,
  "PAK": 1.4953,
  "PER": 1.4953,
  "PHI": 2,
  "POL": 1.6,
  "PUR": 1.4953,
  "QAT": 2.5397,
  "ROU": 1.4953,
  "THA": 1.4953,
  "TPE": 1.497,
  "TUN": 1.4953,
  "TUR": 1.4953,
  "USA": 1.9048,
  "VEN": 1.4953,
  "VIE": 1.4953
};

/** 3:2 — what most federations use, and a safe guess for an asset we lack. */
export const DEFAULT_FLAG_RATIO = 1.5;

/** Federations the AVC TV package supplies a flag for (public/tv-flags). */
export const TV_FLAG_CODES: ReadonlySet<string> = new Set(["AUS","BRN","CHN","HKG","INA","IND","IRI","IRQ","JPN","KAZ","KOR","NZL","OMA","QAT","THA","TPE","VIE"]);

/**
 * Federations public/flags has an asset for.
 *
 * Needed for the same reason as TV_FLAG_CODES and found the same way — the hard
 * way. An SVG <image> pointing at a missing file does not fail quietly: it draws
 * the browser's BROKEN-IMAGE GLYPH, which on the TV overlay (spec/47) is a grey
 * torn-page icon in the flag slot of a live broadcast. The venue boards get away
 * with an onError handler because they use <img>; SVG has no equivalent worth
 * relying on, so the answer has to be known before anything is emitted.
 */
export const FLAG_CODES: ReadonlySet<string> = new Set(["ALG","ARG","AUS","BRA","BRN","BUL","CHI","CHN","CRO","CUB","CZE","DOM","EGY","ESP","FRA","HKG","INA","IND","IRI","IRQ","ITA","JPN","KAZ","KOR","MEX","NZL","OMA","PAK","PER","PHI","POL","PUR","QAT","ROU","THA","TPE","TUN","TUR","USA","VEN","VIE"]);
