// GENERATED by scripts/gen-board-metrics.mjs — do not edit by hand.
//
// Ancorli advance widths in font units, so a board can fit text to a box
// arithmetically on the server. See src/lib/board-text-fit.ts for the fit, and
// the generator for why kern pairs are omitted.

export interface BoardFontMetrics {
  unitsPerEm: number;
  /** Cap height in font units — the boards size text by CAP, not by em. */
  capHeight: number;
  /** Used for any character missing from the table: the widest glyph, so an
   *  unknown name errs towards shrinking rather than overflowing. */
  fallbackAdvance: number;
  advance: Record<string, number>;
}

export const ANCORLI_METRICS: BoardFontMetrics = {
  "unitsPerEm": 1000,
  "capHeight": 700,
  "fallbackAdvance": 1149,
  "advance": {
    "0": 655,
    "1": 325,
    "2": 639,
    "3": 585,
    "4": 607,
    "5": 614,
    "6": 627,
    "7": 554,
    "8": 629,
    "9": 627,
    " ": 353,
    "!": 224,
    "&": 762,
    "'": 193,
    "(": 371,
    ")": 372,
    ",": 198,
    "-": 325,
    ".": 196,
    "/": 494,
    ":": 210,
    "A": 708,
    "B": 642,
    "C": 676,
    "D": 629,
    "E": 566,
    "F": 550,
    "G": 704,
    "H": 665,
    "I": 219,
    "J": 496,
    "K": 632,
    "L": 537,
    "M": 929,
    "N": 725,
    "O": 759,
    "P": 620,
    "Q": 760,
    "R": 659,
    "S": 606,
    "T": 605,
    "U": 683,
    "V": 703,
    "W": 1149,
    "X": 659,
    "Y": 641,
    "Z": 563,
    "À": 708,
    "Á": 708,
    "Â": 708,
    "Ã": 708,
    "Ä": 708,
    "Å": 708,
    "Æ": 1097,
    "Ç": 676,
    "È": 566,
    "É": 566,
    "Ê": 566,
    "Ë": 566,
    "Ì": 219,
    "Í": 219,
    "Î": 220,
    "Ï": 220,
    "Ñ": 725,
    "Ò": 759,
    "Ó": 759,
    "Ô": 759,
    "Õ": 759,
    "Ö": 759,
    "Ø": 761,
    "Ù": 683,
    "Ú": 683,
    "Û": 683,
    "Ü": 683,
    "Ý": 641
  }
};
